### ISSUE TITLE
vBNG setup on OpenStack manually

### ISSUE THREAD

**Issue by taylor** [cncf/onap-demo#4]
Related to CNFs issue https://github.com/cncf/cnfs/issues/8

**Comment by lixuna** [comment]
Building a pre-built VNF Image
---

([Originally source](https://wiki.onap.org/display/DW/ONAP+vCPE+VPP-based+VNF+Installation+and+Usage+Information#ONAPvCPEVPP-basedVNFInstallationandUsageInformation-Buildingapre-builtVNFImage))

Using the vBNG as an example, the following steps are used to create a vBNG image which can then be used as the image for instantiating a v vBNG.

1.  [x] Manually configure the .yaml file to not run the install script
  * [x]  Comment out the last line of base_vcpe_vbng.yaml (i.e. do not invoke v_bng_install.sh via the yaml)
  * [x]  yaml file is at https://github.com/cncf/onap-demo/blob/master/heat/vCPE/vgmux/base_vcpe_vbng.yaml

1. [x] Create a 'stack' - using an appropriately populated .env file
  * See comments below and commits in https://github.com/cncf/onap-demo/tree/vnf_test_noonap/vnf_test/vCPE/vbng
  * [x] openstack stack create -t base_vcpe_vbng.yaml -e base_vcpe_vbng.env vBNG

1. [x] Log into the VM as the 'ubuntu' user and switch to the 'root' user
  * [x] sudo su -
  * [x] cd /opt

1. [x] Create the file "/opt/config/compile_state.txt" with the contents of "build"

1. [x] From /opt, invoke the install script
  * [x] ./v_bng_install.sh
  * [x] This will build vpp and honeycomb code, it may take 30-40 minutes

1. [x] Clean up some files not required for the final image (this will save several gigabytes):
  * [x] rm -fr /opt/vpp /opt/hc2vpp /opt/demo

1. [x] Edit the file "/opt/config/compile_state.txt" and change the contents of the file to "done"
  * [ ]  Note: In the case of the vbrg emulator, the file /opt/config/compile_state.txt is created by 
the base_vcpe_vbrg.yaml file. The compile state (done, auto or build) can be passed into
the vbrg env file before the VNF is created.
  * _Compile state / description_
    - Done	/ Use a prebuilt image. Install script sets up the environment
    - Auto	/ Install script builds honeycomb and vpp and sets up the environment
    - Build	/ Install script builds honeycomb and vpp

1. [x] Reboot

1. [x] Save an image of the VNF
  * [x] openstack server image create --name vbng-base-ubuntu-16-04 <VM Name or ID>
  * [x] "vgmux-base-ubuntu-16-04" will be the name of the new vBNG image


Instantiate a VNF based on the pre-built Image
---

* [x] Change the .env file to use the VNF image created using the process described above.
  * [x] For example - replace "ubuntu-16-04-cloud-amd64" with "vbng-base-ubuntu-16-04" in "vcpe_vbng.env"

* [x] Ensure the .yaml file does not have the install script commented out
  * [x] For example, ensure "v_bng_install.sh" is not commented out in "base_vcpe_vbng.yaml"

* [x] Create a 'stack'
  * [x] openstack stack create -t base_vcpe_vbng.yaml -e base_vcpe_vbng.env vBNG
  * [x] Note, remove the "vBNG" stack that was created during the "Building a VNF Image" stage
  * [x] Using the image created above, the install script will perform some configuration steps and complete much more quickly since the VPP and Honeycomb code has already been compiled.
